// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gswdmdygbytmqkacwngm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdzd2RtZHlnYnl0bXFrYWN3bmdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NDg1ODEsImV4cCI6MjA2MjAyNDU4MX0.o7vGr6X-HsxAAqqu8VDyra6iIpol26EVS9rtvevV0WI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);